### ISSUE TITLE
UnboundLocalError: local variable 'article_list' referenced before assignment

### ISSUE THREAD

**Issue by crazyxiaoj** [Dao-zhi/GoogleScholarGUI#1]
非常感谢您开发此软件！
但是，在使用GoogleScholar-Protable.exe时，出现报错：GoogleScholar.get_data()：[Errno 11001] getaddrinfo failed。设置及报错图片如下图所示。
![image](https://user-images.githubusercontent.com/50630515/191451152-f92d5966-8e96-4db1-baf9-047f59f07d44.png)

**Comment by Dao-zhi** [comment]
你好，根据报错信息来看，可能是代理设置问题，请检查代理设置。


1725805106
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dao-zhi/GoogleScholarGUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 下午4:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Dao-zhi/GoogleScholarGUI] UnboundLocalError: local variable 'article_list' referenced before assignment (Issue #1)





 
非常感谢您开发此软件！
 但是，在使用GoogleScholar-Protable.exe时，出现报错：GoogleScholar.get_data()：[Errno 11001] getaddrinfo failed。设置及报错图片如下图所示。
