### ISSUE TITLE
你好，运行程序后超过等待时间依然没有结果？请问有什么解决方法吗？非常感谢！！

### ISSUE THREAD

**Issue by yolololo-huang** [Dao-zhi/GoogleScholarGUI#2]

**Comment by yolololo-huang** [comment]
非常感谢你开发此软件！！
但输入内容后开始运行一直没有结果，操作进度条也没有反应？
![屏幕截图 2023-04-08 163236](https://user-images.githubusercontent.com/121869396/230712191-b385c55c-bba7-4f50-883b-bd9f0d055e2f.png)

**Comment by yolololo-huang** [comment]
非常感谢你开发软件！！！
不论是否启用反爬都无法获取，请问有什么解决方法吗？
![屏幕截图 2023-04-08 171139](https://user-images.githubusercontent.com/121869396/230713666-0ecaf13c-2cd2-4ada-b7a6-1f967e8719ad.png)
![屏幕截图 2023-04-08 171447](https://user-images.githubusercontent.com/121869396/230713687-4d7abbe6-d658-446a-ad60-3ab34f8dfa24.png)
g)

**Comment by Dao-zhi** [comment]
代理端口号前有一个中文冒号
